### ISSUE TITLE
[Bug] 使用docker构建huasen-server镜像

### ISSUE THREAD

**Issue by starwishes** [huasenjio/huasenjio-compose#12]
### 提交前搜索 issues

- [X] 我已经搜索了[issues](https://github.com/huasenjio/huasenjio-compose/issues)，没有发现类似的问题。

### 环境

Linux

### 源码版本

不清楚

### 功能场景

arm64 Ubuntu 20.04.3 LTS和x86用docker安装会出现
Status: Downloaded newer image for node:16-alpine3.17
 ---> 7453529d5cbe
Step 2/10 : LABEL maintainer="huasen<huasenjio@163.com>"
 ---> Running in 9c54025b8595
 ---> 522cbeca62d6
Step 3/10 : ENV LANG="C.UTF-8"
 ---> Running in bc37dcf93aa2
 ---> 31ad3c7edf84
Step 4/10 : COPY . /app/huasen-server
 ---> 64f8e6fea3ac
Step 5/10 : WORKDIR /app/huasen-server
 ---> Running in 2cdedbb3786b
 ---> fbdb7009f7de
Step 6/10 : RUN npm config set registry http://registry.npm.taobao.org
 ---> Running in 485b24b8e351
 ---> cbaf39644056
Step 7/10 : RUN npm install pm2 -g
 ---> Running in 26c7a48c038b
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 157 packages in 3m
npm notice
npm notice New major version of npm available! 8.19.4 -> 10.2.3
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.3>
npm notice Run `npm install -g npm@10.2.3` to update!
npm notice
 ---> c850d2a60bae
Step 8/10 : RUN npm install
 ---> Running in bfe9d55d47f7
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated superagent@3.8.3: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)

added 708 packages in 2m

40 packages are looking for funding
  run `npm fund` for details
 ---> 88d5ad78a2dc

docker ps -a 

bfe9d55d47f7   c850d2a60bae               "/bin/sh -c 'npm ins…"   26 minutes ago   Exited (0) 23 minutes ago                                                                                          laughing_kepler
26c7a48c038b   cbaf39644056               "/bin/sh -c 'npm ins…"   28 minutes ago   Exited (0) 26 minutes ago                                                                                          goofy_wozniak
485b24b8e351   fbdb7009f7de               "/bin/sh -c 'npm con…"   28 minutes ago   Exited (0) 28 minutes ago                                                                                          blissful_aryabhata

### 复现步骤

就git clone https://github.com/huasenjio/huasenjio-compose.git
然后进入cd huasenjio-compose
然后docker-compose up -d

### 你愿意提交 PR 吗？

- [x] 是的，我愿意提交 PR ！

### 行为准则

- [X] 严格遵守中华人民共和国相关法律，项目仅供大家学习交流，请勿用于商业用途！

**Comment by huasenjio** [comment]
你好，构建huasen-server的时候没有发现报错，warning是因为版本不是最新，不是错误。
