### ISSUE TITLE
[Bug] 添加网链时链接不支持输入IPv6地址

### ISSUE THREAD

**Issue by zjyul** [huasenjio/huasenjio-compose#16]
### 提交前搜索 issues

- [X] 我已经搜索了[issues](https://github.com/huasenjio/huasenjio-compose/issues)，没有发现类似的问题。

### 环境

Linux

### 源码版本

不清楚

### 功能场景

网链添加

### 复现步骤

添加网链,，输入链接如：http://[240e:eb:8001:e02::33]/leftIndex，提示输入正确网址。

### 问题现象

![image](https://github.com/huasenjio/huasenjio-compose/assets/30853659/3990ded9-5a87-423e-a749-0b692cc6d292)

### 你愿意提交 PR 吗？

- [ ] 是的，我愿意提交 PR ！

### 行为准则

- [X] 严格遵守中华人民共和国相关法律，项目仅供大家学习交流，请勿用于商业用途！

**Comment by huasenjio** [comment]
感谢您的建议，我们在下一个版本中，将会支持IPV6的输入，请您留意更新~

**Comment by huasenjio** [comment]
您好，网站已支持ipv6输入了，请知晓，感谢您的建议。

<img width="520" alt="image" src="https://github.com/huasenjio/huasenjio-compose/assets/54260620/243fd3e7-a3a4-4e44-bb3d-b9511a412d29">

**Comment by zjyul** [comment]
收到，感谢👍



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年06月16日 14:59 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [huasenjio/huasenjio-compose] [Bug] 添加网链时链接不支持输入IPv6地址 (Issue #16) |

您好，网站已支持ipv6输入了，请知晓，感谢您的建议。

image.png (view on web)
