### ISSUE TITLE
[Bug] 迁移时遇到错误

### ISSUE THREAD

**Issue by sakiyo18** [huasenjio/huasenjio-compose#17]
### 提交前搜索 issues

- [X] 我已经搜索了[issues](https://github.com/huasenjio/huasenjio-compose/issues)，没有发现类似的问题。

### 环境

Linux

### 源码版本

不清楚

### 功能场景

迁移服务器时

### 复现步骤

上传目录后进入bin目录，运行update.sh。

### 问题现象

迁移目录至其他服务器后运行update.sh后，显示：
正在停止容器...
update.sh: line 10: docker-compose: command not found
正在删除容器...
update.sh: line 13: docker-compose: command not found
正在重新构建服务镜像...
update.sh: line 17: docker-compose: command not found
正在重启容器...
update.sh: line 21: docker-compose: command not found

### 你愿意提交 PR 吗？

- [ ] 是的，我愿意提交 PR ！

### 行为准则

- [X] 严格遵守中华人民共和国相关法律，项目仅供大家学习交流，请勿用于商业用途！

**Comment by huasenjio** [comment]
您好，麻烦发一下update.sh以及你迁移后的目录路径。

**Comment by huasenjio** [comment]
您迁移后的服务器，是不是还没有安装docker和docker-compose呢？

**Comment by sakiyo18** [comment]
> 安装docker和docker-compose

是的，但是我安装完成运行完脚本后，前端账号登录不上，后端管理员账号也登录不上，可能是什么问题呢？
![微信截图_20240502142021](https://github.com/huasenjio/huasenjio-compose/assets/39026267/864dfa15-72db-4ac4-a206-157518988e61)
![微信截图_20240502142337](https://github.com/huasenjio/huasenjio-compose/assets/39026267/9e8a5e80-19e0-4699-a5f3-d790000fe257)

**Comment by sakiyo18** [comment]
已解决，迁移数据库时使用压缩包。
